### PR TITLE
Improve Tall&Narrow profile metadata

### PR DESCRIPTION
**Pull request by raveren**
I noticed the text was too long, and the image too narrow, hopefully it looks allright now:

image

### CODE REVIEW

**Comment by raveren** [comment]
I also added the image width info to the readme

**Comment by TechSupport26** [comment]
We know about the text being a bit long so the buttons are hidden, this will be fixed in the next version so if you could let me know if you still want to change the profile description or leave it as it is.

**Comment by svr333** [comment]
Increasing the version is not entirely necessary on this one as the profile stayed intact, the only thing that change is the description / preview image.
Though increasing it doesn't really matter at all

**Comment by raveren** [comment]
Hi guys, nice to see the blood flowing in open source :))

Yeah, lets keep the old text, I think it's some decent inspiration to try new things :)

If I may add my 2 cents about it, you should always increase the most minor version point with each change :)

**Review by svr333 — APPROVED** [review]

**Pull request merged**
