### PR TITLE
Add Spotify Mini profile

### PR DESCRIPTION
**Pull request by IZeeLikeEyeZee**

### CODE REVIEW

**Comment by svr333** [comment]
Profile looks incredible but I think I want the description to start with a small disclaimer like `(requires font install)`
(just until we have a better way to handle that)

**Review by svr333 — APPROVED** [review]
lgtm! Thank you for your contribution!

**Comment by IZeeLikeEyeZee** [comment]
image
uhh just realized I might've made the description too long haha. feel free to change it as you'd like, I've enabled edits for maintainers :)

**Comment by TechSupport26** [comment]
That's really interesting as I can't actually see or click on the install button. (Could be that my screen resolution is different to yours.)
However, this is fixed in the next update.

**Comment by IZeeLikeEyeZee** [comment]
Ah ok cool, np. The install button wasn't working for me either

**Comment by svr333** [comment]
Yeah the install doesn't work, first thought is is that its the first file with a lot of other files to download but I dont think it downloads at all, so we might have to debug it later on

**Pull request merged**
