### PR TITLE
my profile :)

### PR DESCRIPTION
**Pull request by hauntedandholy**
I hope I'm doing this right 😅

### CODE REVIEW

**Comment by TechSupport26** [comment]
Just to note. Your description is a little long so it has pushed all the buttons down. I will have a look at making this automatically adjust to fit all the text.

**Comment by hauntedandholy** [comment]
I see! Thank you! :)

**Comment by hauntedandholy** [comment]
If need be, I could definitely shorten it in the morning!

**Comment by TechSupport26** [comment]
No need, this will be fixed in the next release. It was bound to happen at some point.  https://github.com/AudioBand/AudioBand/pull/95 Should fix this.
You have made a nice profile. Thanks for contributing :D

**Comment by hauntedandholy** [comment]
Thank you! :)

**Pull request merged**
